[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stock-mcp-server"
version = "0.1.0"
description = "MCP server exposing stock market data using yahooquery"
authors = [{name = "Chintan Diwakar", email = "chintan.diwakar012@gmail.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]

dependencies = [
    "fastapi",
    "uvicorn",
    "yahooquery",
    "pandas",
    "pydantic>=2.0",
    "httpx",
    "rich"
]

[project.scripts]
stock-mcp = "stock_mcp.server:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["stock_mcp*"]
